// scripts/seedProducts.js
import mongoose from "mongoose";
import dotenv from "dotenv";
import Product from "../models/Product.js";

dotenv.config();

const seedProducts = async () => {
  try {
    // connect first
    await mongoose.connect(process.env.MONGO_URI);

    // find last product id after connection
    const lastProduct = await Product.findOne().sort({ numericId: -1 });
    let nextId = lastProduct ? lastProduct.numericId + 1 : 1;

    const products = [
      {
        name: "Dell Inspiron 15 3000 Series",
        description: `Its sleek design, reliable performance, and long-lasting battery, it's perfect for students and professionals on the go.`,
        category: "Electronics",
        specifications: [
          "Processor: Intel Core i5-1135G7, 11th Gen",
          'Display: 15.6" Full HD (1920 x 1080) Anti-Glare LED-Backlit',
          "RAM: 8GB DDR4, expandable up to 16GB",
          "Storage: 512GB SSD",
          "Graphics: Intel Iris Xe Graphics",
          "Operating System: Windows 11 Home",
          "Battery Life: Up to 8 hours",
          "Weight: 1.8 kg",
          "Ports: 2x USB 3.2, 1x USB 2.0, HDMI 1.4, SD Card Reader, Audio Jack",
          "Connectivity: Wi-Fi 6, Bluetooth 5.0",
        ],
        price: 25000,
        numericId: nextId++,
      },
      {
        name: "HP Pavilion 15 Series",
        description:
          "A stylish and versatile laptop for everyday computing and entertainment.",
        category: "Electronics",
        price: 50000,
        specifications: [
          " Processor: Intel Core i5-1135G7, 11th Gen",
          "Display: 15.6' Full HD IPS (1920 x 1080) Micro-Edge",
          "RAM: 8GB DDR4",
          "Storage: 512GB SSD",
          "Graphics: Intel Iris Xe Graphics",
          "Operating System: Windows 11 Home",
          "Battery Life: Up to 9 hours",
          "Weight: 1.75 kg",
          "Ports: 2x USB 3.2, 1x USB-C, HDMI 2.0, Audio Jack",
          "Connectivity: Wi-Fi 6, Bluetooth 5.0",
        ],
        numericId: nextId++,
      },
      {
        name: "Lenovo IdeaPad 3",
        description:
          "Affordable and reliable, ideal for students and home users.",
        category: "Electronics",
        specifications: [
          "Processor: AMD Ryzen 5 5500U",
          "Display: 15.6' Full HD (1920 x 1080) Anti-Glare",
          "RAM: 8GB DDR4",
          "Storage: 256GB SSD",
          "Graphics: Integrated AMD Radeon Graphics",
          "Operating System: Windows 11 Home",
          "Battery Life: Up to 6 hours",
          "Weight: 1.85 kg",
          "Ports: 2x USB 3.1, 1x USB 2.0, HDMI 1.4, SD Card Reader",
          "Connectivity: Wi-Fi 5, Bluetooth 4.2",
        ],
        price: 60000,
        numericId: nextId++,
      },
      {
        name: "ASUS VivoBook 15",
        category: "Electronics",
        description:
          "Lightweight and portable, designed for productivity and entertainment.",
        specifications: [
          "Processor: Intel Core i3-1215U, 12th Gen",
          "Display: 15.6' Full HD NanoEdge (1920 x 1080)",
          "RAM: 4GB DDR4",
          "Storage: 256GB SSD",
          "Graphics: Integrated Intel UHD Graphics",
          "Operating System: Windows 11 Home",
          "Battery Life: Up to 8 hours",
          "Weight: 1.7 kg",
          "Ports: 2x USB 3.2, 1x USB-C, HDMI 1.4",
          "Connectivity: Wi-Fi 6, Bluetooth 5.1",
        ],
        price: 89999,
        numericId: nextId++,
      },
      {
        name: "Apple MacBook Air (M1)",
        description:
          "Ultra-sleek and powerful, perfect for professionals and creators.",
        category: "Electronics",
        specifications: [
          "Processor: Apple M1 Chip with 8-Core CPU",
          "Display: 13.3' Retina Display (2560 x 1600)",
          "RAM: 8GB Unified Memory",
          "Storage: 256GB SSD",
          "Graphics: Integrated 7-Core GPU",
          "Operating System: macOS",
          "Battery Life: Up to 15 hours",
          "Weight: 1.29 kg",
          "Ports: 2x Thunderbolt/USB 4, 1x Headphone Jack",
          "Connectivity: Wi-Fi 6, Bluetooth 5.0",
        ],
        price: 100000,
        numericId: nextId++,
      },
      {
        name: "Acer Aspire 5",
        description:
          "A budget-friendly laptop with solid performance for daily tasks.",
        category: "Electronics",
        specifications: [
          " Processor: Intel Core i5-1135G7, 11th Gen",
          "Display: 15.6' Full HD IPS (1920 x 1080) Micro-Edge",
          "RAM: 8GB DDR4",
          "Storage: 512GB SSD",
          "Graphics: Intel Iris Xe Graphics",
          "Operating System: Windows 11 Home",
          "Battery Life: Up to 9 hours",
          "Weight: 1.75 kg",
          "Ports: 2x USB 3.2, 1x USB-C, HDMI 2.0, Audio Jack",
          "Connectivity: Wi-Fi 6, Bluetooth 5.0",
        ],
        price: 99000,
        numericId: nextId++,
      },
      {
        name: "MSI GF63 Thin",
        description:
          "A slim gaming laptop offering great value for casual gamers.",
        category: "Electronics",
        specifications: [
          " Processor: Intel Core i5-1135G7, 11th Gen",
          "Display: 15.6' Full HD IPS (1920 x 1080) Micro-Edge",
          "RAM: 8GB DDR4",
          "Storage: 512GB SSD",
          "Graphics: Intel Iris Xe Graphics",
          "Operating System: Windows 11 Home",
          "Battery Life: Up to 9 hours",
          "Weight: 1.75 kg",
          "Ports: 2x USB 3.2, 1x USB-C, HDMI 2.0, Audio Jack",
          "Connectivity: Wi-Fi 6, Bluetooth 5.0",
        ],
        price: 55600,
        numericId: nextId++,
      },
      {
        name: "Razer Blade 14",
        description: "A premium gaming laptop with high-end performance.",
        category: "Electronics",
        specifications: [
          " Processor: Intel Core i5-1135G7, 11th Gen",
          "Display: 15.6' Full HD IPS (1920 x 1080) Micro-Edge",
          "RAM: 8GB DDR4",
          "Storage: 512GB SSD",
          "Graphics: Intel Iris Xe Graphics",
          "Operating System: Windows 11 Home",
          "Battery Life: Up to 9 hours",
          "Weight: 1.75 kg",
          "Ports: 2x USB 3.2, 1x USB-C, HDMI 2.0, Audio Jack",
          "Connectivity: Wi-Fi 6, Bluetooth 5.0",
        ],
        price: 75600,
        numericId: nextId++,
      },
      {
        name: "Samsung Galaxy Book Pro 360",
        category: "Electronics",
        description:
          "A 2-in-1 convertible laptop with AMOLED display for flexibility and vibrant visuals.",
        specifications: [
          " Processor: Intel Core i5-1135G7, 11th Gen",
          "Display: 15.6' Full HD IPS (1920 x 1080) Micro-Edge",
          "RAM: 8GB DDR4",
          "Storage: 512GB SSD",
          "Graphics: Intel Iris Xe Graphics",
          "Operating System: Windows 11 Home",
          "Battery Life: Up to 9 hours",
          "Weight: 1.75 kg",
          "Ports: 2x USB 3.2, 1x USB-C, HDMI 2.0, Audio Jack",
          "Connectivity: Wi-Fi 6, Bluetooth 5.0",
        ],
        price: 71500,
        numericId: nextId++,
      },
      {
        name: "Microsoft Surface Laptop 4",
        category: "Electronics",
        description:
          "A sleek and powerful laptop with a premium design for productivity.",
        specifications: [
          " Processor: Intel Core i5-1135G7, 11th Gen",
          "Display: 15.6' Full HD IPS (1920 x 1080) Micro-Edge",
          "RAM: 8GB DDR4",
          "Storage: 512GB SSD",
          "Graphics: Intel Iris Xe Graphics",
          "Operating System: Windows 11 Home",
          "Battery Life: Up to 9 hours",
          "Weight: 1.75 kg",
          "Ports: 2x USB 3.2, 1x USB-C, HDMI 2.0, Audio Jack",
          "Connectivity: Wi-Fi 6, Bluetooth 5.0",
        ],
        price: 59000,
        numericId: nextId++,
      },
      {
        name: "Sony Bravia 55-inch 4K TV",
        category: "Electronics",
        description:
          "Experience vivid colors and crisp clarity with this 4K TV.",
        specifications: [
          "Display: 55-inch 4K LED",
          "Resolution: 3840 x 2160",
          "HDR: Yes (HDR10, Dolby Vision)",
          "Sound: Dolby Atmos",
          "Connectivity: HDMI, USB, Wi-Fi, Bluetooth",
          "Smart TV: Yes (Android TV)",
          "Voice Assistant: Google Assistant, Alexa",
          "Weight: 17.4kg",
          "Dimensions: 1235 x 775 x 55 mm",
          "Energy Efficiency: A++",
        ],
        price: 65000,
        numericId: nextId++,
      },
      {
        name: "Samsung Galaxy S23 Ultra",
        category: "Electronics",
        description:
          "Capture stunning photos and videos with the ultra-powerful camera.",
        specifications: [
          "Display: 6.8-inch Dynamic AMOLED 2X",
          "Processor: Qualcomm Snapdragon 8 Gen 2",
          "RAM: 12GB",
          "Storage: 256GB/512GB",
          "Camera: 200MP Quad Camera System",
          "Operating System: Android 13",
          "Battery: 5000mAh",
          "Connectivity: 5G, Wi-Fi 6, Bluetooth 5.2",
          "Weight: 228g",
          "Dimensions: 163.4 x 78.1 x 8.9 mm",
        ],
        price: 110000,
        numericId: nextId++,
      },
      {
        name: "Apple iPhone 14 Pro Max",
        category: "Electronics",
        description:
          "Premium smartphone with A16 Bionic chip and ProMotion display.",
        specifications: [
          "Display: 6.7-inch Super Retina XDR",
          "Processor: A16 Bionic chip",
          "RAM: 6GB",
          "Storage: 128GB/256GB/512GB/1TB",
          "Camera: 48MP Triple Camera System",
          "Operating System: iOS 16",
          "Battery: 4323mAh",
          "Connectivity: 5G, Wi-Fi 6, Bluetooth 5.3",
          "Weight: 240g",
          "Dimensions: 160.8 x 78.1 x 7.85 mm",
        ],
        price: 130000,
        numericId: nextId++,
      },
      {
        name: "Bose QuietComfort 45 Headphones",
        category: "Electronics",
        description:
          "World-class noise-cancelling headphones for immersive sound.",
        specifications: [
          "Noise Cancelling: Yes (Adjustable)",
          "Connectivity: Bluetooth 5.1, Wired (3.5mm jack)",
          "Battery Life: Up to 24 hours",
          "Weight: 240g",
          "Dimensions: 18 x 18 x 8 cm",
          "Microphone: Built-in",
          "Voice Assistant: Google Assistant, Alexa",
          "Charging Time: 2 hours",
          "Audio: Active EQ, Volume-optimized EQ",
        ],
        price: 30000,
        numericId: nextId++,
      },
      {
        name: "Canon EOS R6 Camera",
        category: "Electronics",
        description: "Capture high-quality images with this mirrorless camera.",
        specifications: [
          "Sensor: Full-frame CMOS",
          "Resolution: 20MP",
          "ISO Range: 100-102400 (expandable)",
          "Video: 4K at 60fps",
          "Autofocus: Dual Pixel CMOS AF II",
          "Connectivity: Wi-Fi, Bluetooth",
          "Battery Life: 380 shots",
          "Weight: 680g",
          "Dimensions: 138.4 x 98.1 x 88.4 mm",
        ],
        price: 220000,
        numericId: nextId++,
      },
      {
        name: "Apple MacBook Pro 14-inch",
        category: "Electronics",
        description: "The powerful laptop for professionals with M1 Pro chip.",
        specifications: [
          "Processor: Apple M1 Pro chip",
          "Display: 14-inch Retina Display (3024 x 1964)",
          "RAM: 16GB/32GB",
          "Storage: 512GB/1TB/2TB",
          "Graphics: Integrated 14-core GPU",
          "Operating System: macOS Monterey",
          "Battery Life: Up to 17 hours",
          "Weight: 1.6kg",
          "Dimensions: 31.26 x 22.12 x 1.55 cm",
        ],
        price: 199000,
        numericId: nextId++,
      },
      {
        name: "Samsung Galaxy Tab S8 Ultra",
        category: "Electronics",
        description: "Large tablet with high-end features and display.",
        specifications: [
          "Display: 14.6-inch Super AMOLED",
          "Processor: Qualcomm Snapdragon 8 Gen 1",
          "RAM: 8GB/12GB",
          "Storage: 128GB/256GB",
          "Camera: 13MP Rear, 12MP Front",
          "Operating System: Android 12",
          "Battery: 11200mAh",
          "Connectivity: 5G, Wi-Fi 6, Bluetooth 5.2",
          "Weight: 726g",
          "Dimensions: 326.4 x 208.6 x 5.5 mm",
        ],
        price: 95000,
        numericId: nextId++,
      },
      {
        name: "LG OLED65CXPUA Alexa Built-In OLED TV",
        category: "Electronics",
        description:
          "Enjoy stunning visuals with OLED display and smart features.",
        specifications: [
          "Display: 65-inch OLED",
          "Resolution: 4K UHD",
          "HDR: Dolby Vision, HDR10, HLG",
          "Sound: Dolby Atmos, AI Sound Pro",
          "Smart TV: Yes (webOS)",
          "Voice Assistant: Alexa, Google Assistant",
          "Connectivity: HDMI, USB, Wi-Fi, Bluetooth",
          "Energy Efficiency: A+",
          "Weight: 25.9kg",
          "Dimensions: 1440 x 834 x 46 mm",
        ],
        price: 180000,
        numericId: nextId++,
      },
      {
        name: "Microsoft Surface Pro 8",
        category: "Electronics",
        description: "2-in-1 tablet with laptop performance and portability.",
        specifications: [
          "Display: 13-inch PixelSense Flow",
          "Processor: Intel Core i7-1185G7",
          "RAM: 8GB/16GB",
          "Storage: 128GB/256GB/512GB",
          "Camera: 10MP Rear, 5MP Front",
          "Operating System: Windows 11",
          "Battery: 32.5Wh (Up to 16 hours)",
          "Weight: 891g",
          "Dimensions: 287.6 x 208.3 x 9.3 mm",
        ],
        price: 85000,
        numericId: nextId++,
      },
      {
        name: "GoPro HERO10 Black",
        category: "Electronics",
        description: "Capture every adventure in stunning 5.3K video.",
        specifications: [
          "Video: 5.3K at 60fps",
          "Camera: 23MP",
          "Waterproof: Yes (up to 10m)",
          "Connectivity: Wi-Fi, Bluetooth",
          "Battery: 1720mAh",
          "Weight: 153g",
          "Dimensions: 71 x 55 x 33 mm",
          "Voice Control: Yes",
          "Mount: GoPro Mounting System",
        ],
        price: 45000,
        numericId: nextId++,
      },

      {
        name: "Men's T-Shirt",
        category: "Fashion",
        description: "Comfortable cotton t-shirt in various sizes and colors.",
        price: 599,
        specifications: [
          "Material: 100% Cotton",
          "Available Sizes: S, M, L, XL",
          "Colors: Black, White, Blue, Grey",
          "Fit: Regular",
          "Care Instructions: Machine washable",
          "Weight: 200g",
        ],
        numericId: nextId++,
      },
      {
        name: "Women's Jacket",
        category: "Fashion",
        description: "Stylish and warm jacket for all seasons.",
        price: 2499,
        specifications: [
          "Material: Polyester and Wool Blend",
          "Available Sizes: XS, S, M, L, XL",
          "Colors: Black, Navy, Grey",
          "Closure: Zipper",
          "Care Instructions: Dry clean only",
          "Weight: 800g",
        ],
        numericId: nextId++,
      },
      {
        name: "Men's Jeans",
        category: "Fashion",
        description: "Classic blue jeans with a slim fit.",
        price: 1499,
        specifications: [
          "Material: 98% Cotton, 2% Elastane",
          "Fit: Slim",
          "Available Sizes: 28, 30, 32, 34, 36",
          "Colors: Blue",
          "Closure: Button Fly",
          "Care Instructions: Machine washable",
          "Weight: 500g",
        ],
        numericId: nextId++,
      },
      {
        name: "Women's Dress",
        category: "Fashion",
        description: "Elegant evening dress, perfect for parties.",
        price: 2999,
        specifications: [
          "Material: Satin Polyester",
          "Available Sizes: XS, S, M, L, XL",
          "Colors: Red, Black, Navy",
          "Fit: A-Line",
          "Care Instructions: Hand wash",
          "Weight: 600g",
        ],
        numericId: nextId++,
      },
      {
        name: "Unisex Sneakers",
        category: "Fashion",
        description: "Comfortable and trendy sneakers for all occasions.",
        price: 1999,
        specifications: [
          "Material: Synthetic Leather and Mesh",
          "Available Sizes: 6, 7, 8, 9, 10, 11",
          "Colors: White, Black, Grey",
          "Sole: Rubber",
          "Closure: Lace-up",
          "Care Instructions: Wipe with a damp cloth",
          "Weight: 450g",
        ],
        numericId: nextId++,
      },
      {
        name: "Men's Hoodie",
        category: "Fashion",
        description: "Soft and cozy hoodie for chilly weather.",
        price: 1799,
        specifications: [
          "Material: 80% Cotton, 20% Polyester",
          "Available Sizes: S, M, L, XL",
          "Colors: Black, Grey, Navy",
          "Fit: Regular",
          "Care Instructions: Machine washable",
          "Weight: 500g",
        ],
        numericId: nextId++,
      },
      {
        name: "Women's Skirt",
        category: "Fashion",
        description: "A fashionable skirt for casual and formal wear.",
        price: 999,
        specifications: [
          "Material: 100% Polyester",
          "Available Sizes: XS, S, M, L",
          "Colors: Black, Beige, Blue",
          "Fit: A-Line",
          "Care Instructions: Machine washable",
          "Weight: 300g",
        ],
        numericId: nextId++,
      },
      {
        name: "Leather Belt",
        category: "Fashion",
        description: "High-quality leather belt with a stylish buckle.",
        price: 799,
        specifications: [
          "Material: Genuine Leather",
          "Width: 3.5 cm",
          "Colors: Brown, Black",
          "Buckle: Metal",
          "Length: 30-40 inches",
          "Care Instructions: Wipe with a damp cloth",
        ],
        numericId: nextId++,
      },
      {
        name: "Fashion Sunglasses",
        category: "Fashion",
        description: "Trendy sunglasses to protect your eyes in style.",
        price: 1299,
        specifications: [
          "Material: Plastic Frame, UV400 Lenses",
          "Available Colors: Black, Tortoise Shell, Grey",
          "Lens Type: Polarized",
          "Protection: UV Protection",
          "Weight: 150g",
        ],
        numericId: nextId++,
      },
      {
        name: "Men's Watch",
        category: "Fashion",
        description: "Classic men's watch with a stainless steel band.",
        price: 4999,
        specifications: [
          "Material: Stainless Steel",
          "Movement: Quartz",
          "Case Diameter: 42mm",
          "Water Resistance: 50m",
          "Band Width: 22mm",
          "Colors: Silver, Black",
          "Weight: 150g",
        ],
        numericId: nextId++,
      },
      {
        name: "Apple",
        category: "Grocery",
        description: "Fresh and crunchy apples",
        price: 100,
        specifications: [
          "Type: Red, Green, or Yellow Apples",
          "Origin: Locally sourced",
          "Weight: 1 kg",
          "Storage: Keep in a cool place",
          "Best Before: 7 days from purchase",
        ],
        numericId: nextId++,
      },
      {
        name: "Banana",
        category: "Grocery",
        description: "Ripe bananas, perfect for smoothies",
        price: 40,
        specifications: [
          "Type: Cavendish Bananas",
          "Origin: Locally sourced",
          "Ripeness: Ripe",
          "Weight: 1 kg",
          "Storage: Keep at room temperature",
          "Best Before: 3-4 days from purchase",
        ],
        numericId: nextId++,
      },
      {
        name: "Carrot",
        category: "Grocery",
        description: "Organic carrots for healthy meals",
        price: 60,
        specifications: [
          "Type: Organic Carrots",
          "Weight: 1 kg",
          "Storage: Keep in a cool, dry place",
          "Best Before: 1 week from purchase",
        ],
        numericId: nextId++,
      },
      {
        name: "Potato",
        category: "Grocery",
        description: "Fresh potatoes for your daily needs",
        price: 50,
        specifications: [
          "Type: White Potatoes",
          "Weight: 1 kg",
          "Storage: Store in a cool, dark place",
          "Best Before: 1-2 weeks from purchase",
        ],
        numericId: nextId++,
      },
      {
        name: "Onion",
        category: "Grocery",
        description: "Fresh onions, essential for cooking",
        price: 30,
        specifications: [
          "Type: Yellow, Red, or White Onions",
          "Weight: 1 kg",
          "Storage: Keep in a cool, dry place",
          "Best Before: 2 weeks from purchase",
        ],
        numericId: nextId++,
      },
      {
        name: "Tomato",
        category: "Grocery",
        description: "Juicy tomatoes, perfect for salads",
        price: 40,
        specifications: [
          "Type: Red Tomatoes",
          "Weight: 1 kg",
          "Storage: Keep at room temperature",
          "Best Before: 3-5 days from purchase",
        ],
        numericId: nextId++,
      },
      {
        name: "Spinach",
        category: "Grocery",
        description: "Organic spinach, packed with nutrients",
        price: 80,
        specifications: [
          "Type: Organic Spinach",
          "Weight: 250g",
          "Storage: Keep in the fridge",
          "Best Before: 3-4 days from purchase",
        ],
        numericId: nextId++,
      },
      {
        name: "Cucumber",
        category: "Grocery",
        description: "Fresh cucumbers, ideal for snacks",
        price: 35,
        specifications: [
          "Type: English Cucumbers",
          "Weight: 1 kg",
          "Storage: Keep in the fridge",
          "Best Before: 1 week from purchase",
        ],
        numericId: nextId++,
      },
      {
        name: "Garlic",
        category: "Grocery",
        description: "Fresh garlic for your daily cooking",
        price: 20,
        specifications: [
          "Type: Fresh Garlic Bulbs",
          "Weight: 250g",
          "Storage: Keep in a cool, dry place",
          "Best Before: 1 month from purchase",
        ],
        numericId: nextId++,
      },
      {
        name: "Lettuce",
        category: "Grocery",
        description: "Fresh lettuce for salads and wraps",
        price: 50,
        specifications: [
          "Type: Romaine or Iceberg Lettuce",
          "Weight: 250g",
          "Storage: Keep in the fridge",
          "Best Before: 3-4 days from purchase",
        ],
        numericId: nextId++,
      },
      // 🔁 Add the rest of your hardcoded products here in the same shape
    ];

    // clear old data before seeding
    await Product.deleteMany();
    await Product.create(products);

    console.log("Products seeded successfully!");
    process.exit();
  } catch (error) {
    console.error("Error seeding products:", error);
    process.exit(1);
  }
};

seedProducts();